### ISSUE TITLE
运行后获取了课程视频的列表然后就结束了

### ISSUE THREAD

**Issue by ipatpat** [Tsuk1ko/uooconline-learner#1]
难受。成功获取了该视频的章节的标题。cookies也是没错了。
是不是因为我的网课是闯关式学习唉。

**Comment by Tsuk1ko** [comment]
如果是闯关模式会抛出异常

**Comment by ipatpat** [comment]
刚想补充一下发现你马上就回复啦。谢谢你哦不过现在挺晚咯，注意睡眠哦。
“
获取了所有章节的标题之后
没有继续获取章节下面的小节
然后就结束了
没有报error”
那我还是老老实实去刷课吧，辛苦啦Tsuk1ko。

**Comment by Tsuk1ko** [comment]
马上就睡了~

这种问题靠我自己没办法解决了，每个人的情况不一样_(:3」∠)_
