### ISSUE TITLE
无法刷客

### ISSUE THREAD

**Issue by Mr-huangyh** [Tsuk1ko/uooconline-learner#2]
undefined 4.1  XXXXXXXXXXX
TypeError: Cannot read property 'replace' of null
    at UoocClient.learn (D:\uooconline-learner-master\src\uoocclient.
js:127:33)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by Mr-huangyh** [comment]
已解决，clogln了一下，
> { id: 1597372065,
    course_id: 412793195,
    title: null,
    content:
     'XXXXXXXXX',
    uri: null,
    type: '60',
    is_task: '0',
    task_id: 0,
    discuss_id: 0,
    sort: '1',
    parent: '0',
    transcode_url: null,
    _level: 1,
    pid: 0,
    catalog_id: 1915095894,
    h5_url: '/app/resourceText?id=1597372065&cid=412793195',
    quiz: [],
    video_pos: 0,
    finished: 0,
    pay_status: 0 } ]
title = null和null属性重名，目前解决方案，在127行增加一个if条件if (resource.title == null) {continue;}

**Comment by Mr-huangyh** [comment]
部分夹带在文本和文本之间的视频链接无法读取

**Comment by Tsuk1ko** [comment]
感谢提出问题，但是抱歉，这个项目不再维护，因课程的不同可能出现很多问题，我在写的时候也没办法考虑全面，仅仅能保证我自己能正常用而已

我这些代码只是提供了刷课大致流程，出现问题自己有能力解决是最好的

**Comment by Mr-huangyh** [comment]
那我可以请问下，您学的课程，和使用的模式吗？另外，完善后，我想作为商业用途，您同意吗？

**Comment by Tsuk1ko** [comment]
我曾经学的什么课程应该和程序的运行没有什么关系吧……模式我不知道指的是什么

GPL 3.0 开源协议不禁止商用，但有开源要求

https://www.zhihu.com/question/19703551

**Comment by Mr-huangyh** [comment]
好的，谢谢，课程和是否为闯关模式，只是想了解一下，我作为一个参考，不作其他用途

**Comment by Mr-huangyh** [comment]
问题已经jie

**Comment by Tsuk1ko** [comment]
是闯关模式
